# <a id='toc1_'></a>[beancount-jupyter notebook for exploaring a beancount file](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- [beancount-jupyter notebook for exploaring a beancount file](#toc1_)    
  - [Checks](#toc1_1_)    
    - [Beancount built in checks](#toc1_1_1_)    
  - [Equivalent entries in singe currency](#toc1_2_)    
  - [Chart of accounts](#toc1_3_)    
  - [Financial overview](#toc1_4_)    
  - [Exploring expenses](#toc1_5_)    
  - [Filtering spesific transactions](#toc1_6_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [ ]:
#@title Importing modules

try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# Run shell commands only in Colab
if IN_COLAB:
    %pip install beanquery
    %pip install git+https://github.com/Ev2geny/evbeantools.git@develop_pr
    %pip install requests

    print("Packages installed in Colab environment")
else:
    print("Running locally, skipping pip install")

import os
import re
from io import StringIO
import datetime
from collections.abc import Iterable

import pandas as pd
import numpy as np
from pandas.io.formats.style import Styler

import requests

import plotly.express as px
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

import plotly.graph_objects as go
import plotly.io as pio

from beancount.loader import load_file, load_string
from beancount.parser import printer
from beancount.parser.printer import print_entries

from beancount.core.data import Transaction, Posting, Open, Close, Balance, Price, Note, Event, Query, Custom

from evbeantools.sing_curr_conv import get_equiv_sing_curr_entries
from evbeantools.juptools import  add_total, beanquery2df,  get_net_worths, get_bean_pivot, prepare_sunburst_data_input, remove_empty_rows, get_period_end_dates, highlight_rows
from evbeantools.juptools import get_sunburst_figure_from_pivot
from evbeantools.beanfuncs import check_mult_funds_in_transit, split_posting
from evbeantools.printer_rich import display_entries

if IN_COLAB:
    import requests

Running locally, skipping pip install

<style>
h1 { color: purple; }
h2 { color: orange; }
</style>

In [ ]:
FILE_URL = "https://raw.githubusercontent.com/beancount/fava/main/contrib/examples/example.beancount"

BEAN_FILE_NAME = "example-fava.beancount"

IN_COLAB = True

if IN_COLAB:
    response = requests.get(FILE_URL)

    # Check if the request was successful
    if response.status_code == 200:
        entries, errors, opts = load_string(response.text)
    else:
        print(f"Failed to download file. Status code: {response.status_code}")

else:
    entries, errors, opts = load_file(BEAN_FILE_NAME)

CURR = opts["operating_currency"][0]

## <a id='toc1_1_'></a>[Checks](#toc0_)

### <a id='toc1_1_1_'></a>[Beancount built in checks](#toc0_)

In [ ]:
printer.print_errors(errors)

## <a id='toc1_2_'></a>[Equivalent entries in singe currency](#toc0_)

In [ ]:
entries_eq, errors_eq, opts_eq = get_equiv_sing_curr_entries(entries, opts, target_currency=CURR, self_testing_mode=True)

## <a id='toc1_3_'></a>[Chart of accounts](#toc0_)

In [ ]:
#@title getting Chart of Accounts
coa_query = """
SELECT account, open.currencies as currencies, open.date as open_date, close.date as close_date
FROM #accounts
ORDER BY account
"""

coa_df = beanquery2df(entries, opts, coa_query).fillna("")
coa_df.set_index("account", inplace=True)

coa_df_styled = coa_df.style.set_table_styles([
    {'selector': 'th.row_heading',  # Targets the index column
     'props': [('text-align', 'left')]}
])

coa_df_styled

## <a id='toc1_4_'></a>[Financial overview](#toc0_)

Financial overview combines information about the changes of the Total Net Worth over time as well as the factors, which caused these changes

In [ ]:
#@title Defining get_fin_overview_table function

def get_fin_overview_table(entries,
                           opts,
                           freq,
                           foc:dict,
                           *,
                           start_period = None,
                           qnt_periods = None,
                           end_period = None,
                           currency = None) -> Styler:
    """
    Function to get the financial overview table for the period from start_period to end_period

    params:
        entries: list of entries
        opts: dict of options
        freq: str
            pandas period alias (Y, Q, M, W, D)
                https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries-period-aliases
                
        foc: financial overview configuration dictionary

        start_period: Period, str, datetime, date or pandas.Timestamp  . pandas timeperiod representation
                    If not provided, the first date of the first entry will be used to determine the start_period

        qnt_periods: int
            number of periods to display

        end_period: Period, str, datetime, date or pandas.Timestamp  . pandas timeperiod representation
                    Used only if qnt_periods is not provided.
                    If not provided, the last date of the last entry will be used to determine the end_period

    """
    if not start_period:
        start_period = pd.Period(entries[0].date, freq)
    else:
        start_period = pd.Period(start_period, freq)

    if qnt_periods:
        end_period = start_period + qnt_periods - 1
    else:
        if not end_period:
            end_period = pd.Period(entries[-1].date, freq)
        else:
            end_period = pd.Period(end_period, freq)

    if not currency:
        currency = opts["operating_currency"][0]

    # This is just to show types
    start_period: pd.Period = start_period
    end_period: pd.Period = end_period

    start_date_iso_str = start_period.start_time.strftime("%Y-%m-%d")
    end_date_iso_str = end_period.end_time.strftime("%Y-%m-%d")

    def get_table_line(query, name):
        """Performs standard actions to create a table line

        Returns:
            _type_: _description_
        """
        df = beanquery2df(entries, opts,  query)
        df['period'] = pd.PeriodIndex(df['date'], freq=freq)
        df_pivot = df.pivot_table(values=f'amount ({currency})',
                                  aggfunc='sum', columns='period')
        df_pivot.index = [name]
        return df_pivot

    query_exp=f"""
            select id, date, CONVERT(position,'{currency}', date) as amount, narration
            WHERE
               ({foc["expenses"]["sql"]}) AND
                date >= {start_date_iso_str} AND
                date <= {end_date_iso_str}
            """
    df_expen_pivot_line = get_table_line(query_exp, foc["expenses"]["name"])

    # print(df_expen_pivot_line)


    query_income = f"""
            select id, date, CONVERT(position,'{currency}',date) as amount, narration
            WHERE
                ({foc["income"]["sql"]})  AND
                date >= {start_date_iso_str} AND
                date <= {end_date_iso_str}
            """

    df_income_pivot_line = get_table_line(query_income, foc["income"]["name"])

    # print(df_income_pivot_line)

    query_gains = f"""
            select id, date, CONVERT(position,'{currency}',date) as amount, narration
            WHERE
                ({foc["gains"]["sql"]}) AND
                date >= {start_date_iso_str} AND
                date <= {end_date_iso_str}
            """

    df_gains_pivot_line = get_table_line(query_gains, foc["gains"]["name"])


    query_equity=f"""
            select id, date, CONVERT(position,'{currency}',date) as amount, narration
            WHERE
               ({foc["equity"]["sql"]}) AND
                date >= {start_date_iso_str} AND
                date <= {end_date_iso_str}
            """
    df_equity_pivot_line = get_table_line(query_equity, foc["equity"]["name"])

    # print(df_equity_pivot_line)


    df_result = pd.concat([df_expen_pivot_line, df_income_pivot_line, df_gains_pivot_line, df_equity_pivot_line])

    df_result = add_total(df_result, col_total_name=foc["total_nw_change"])

    # for the purposes of NW calculation we need to calculate NW also for the start_period -1
    net_worth_dates: list[datetime.date] = get_period_end_dates(start_period -1 , end_period)




    neth_worths:pd.DataFrame = get_net_worths(entries, opts, net_worth_dates, currency, num_acc_components_from_root=1, repeat_row_labels=False)

    # print("---------neth_worths -------------")
    # print(neth_worths)
    # neth_worths.columns = neth_worths.columns.droplevel(0)

    # This line converts
    neth_worths = neth_worths.loc[:,f"amount ({currency})"]

    # print('-------- neth_worths = neth_worths.loc[:,f"amount ({currency})"] -------------')
    # print(neth_worths)

    # neth_worths.set_index('acc_L0', inplace=True)
    neth_worths = add_total(neth_worths, col_total_name=foc["total_nw"])

    neth_worths.columns = pd.to_datetime(neth_worths.columns).to_period(freq)


    # print(neth_worths)

    # Adding the net worths to the result
    df_result = pd.concat([df_result, neth_worths], axis=0)

    # print(df_result)

    df_result = df_result.reindex(sorted(df_result.columns), axis=1)

    df_result.fillna(0, inplace=True)


    df_result.loc[foc["unexplained_diff"]] = float('nan')

    df_result.loc[foc["unexplained_diff"], df_result.columns[1:]] = (
        df_result.loc[foc["total_nw"],
        df_result.columns[1:]] - df_result.loc[foc["total_nw"],
        df_result.columns[:-1]].values + df_result.loc[foc["total_nw_change"],
        df_result.columns[1:]].values
    )

    df_result = highlight_rows(df_result, {foc["total_nw_change"]: "lightblue", foc["total_nw"]: "lightgreen"} )


    return df_result


foc = {"income":{"name": "Income",
                            "sql": "account ~'^Income'  AND not account ~'^Income:Unrealized'"},

                  "gains":{"name": "UnrealGains",
                            "sql": "account ~'^Income:Unrealized'"},

                  "expenses":{"name": "Expenses",
                            "sql": "account ~'^Expenses'"},

                  "equity":{"name": "Equity",
                            "sql": "account ~'^Equity'"},

                  "total_nw_change": "Total Net  Worth Change",

                  "total_nw": "Total Net Worth",

                  "unexplained_diff": "Unexplained difference"
                  }

In [47]:
fin_overview_table = get_fin_overview_table(entries_eq, opts_eq, "Q", foc, currency = "USD")

fin_overview_table

In [59]:
#@title def show_fin_overview_data
def get_fin_overview_fig(fin_overview_table: Styler, foc):
    df_t = fin_overview_table.data.T
    df_t.index = df_t.index.astype(str)

    # Flip the sign of specific columns
    cols_to_change_sign = [
                           foc["income"]["name"],
                           foc["gains"]["name"],
                           foc["equity"]["name"],
                           foc["total_nw_change"]
                           ]
    df_t[cols_to_change_sign] = -df_t[cols_to_change_sign]

    # Define the rows for bar and line plots
    bar_rows = [foc["equity"]["name"],
                foc["expenses"]["name"],
                foc["income"]["name"],
                foc["gains"]["name"],
                foc["total_nw_change"]
                ]

    line_rows = [
                 foc["total_nw"]]

    # Create the figure
    fig = go.Figure()

    # Add bar traces (grouped bars)
    for col in bar_rows:
        fig.add_trace(go.Bar(
            x=df_t.index,
            y=df_t[col],
            name=col,
            yaxis='y1'
        ))

    # Add line traces on secondary y-axis
    for col in line_rows:
        fig.add_trace(go.Scatter(
            x=df_t.index,
            y=df_t[col],
            name=col,
            yaxis='y2',
            mode='lines+markers'
        ))

    # Update layout with dual y-axes
    fig.update_layout(
        title="Financial Overview",
        xaxis=dict(
            title="Period",
            showgrid=True,           # Enables vertical gridlines
            gridcolor='lightgray',   # Optional: change gridline color
            gridwidth=1              # Optional: set gridline thickness
        ),
        yaxis=dict(
            title="P&L",
            showgrid=True,
            gridcolor='gray',
            gridwidth=1,
            zeroline=True
        ),
        yaxis2=dict(
            title="Net Worth",
            overlaying='y',
            side='right',
            showgrid=True,
            range=[0, df_t[line_rows].max().max()*1.2]
        ),
        barmode='group',
        legend=dict(x=1.05, y=1),

        height=800,         # You can still fix the height
        autosize=True,      # Enable automatic sizing

        margin=dict(l=40, r=40, t=60, b=40)
    )

    return fig

In [60]:
fin_overview_fig = get_fin_overview_fig(fin_overview_table, foc)
fin_overview_fig.show()

## <a id='toc1_5_'></a>[Exploring expenses](#toc0_)

In [61]:
def get_expenses_df_pivot(entries,
                           opts,
                           freq,
                           *,
                           start_period = None,
                           qnt_periods = None,
                           end_period = None,
                           currency = None) -> Styler:

    if not start_period:
        start_period = pd.Period(entries[0].date, freq)
    else:
        start_period = pd.Period(start_period, freq)

    if qnt_periods:
        end_period = start_period + qnt_periods - 1
    else:
        if not end_period:
            end_period = pd.Period(entries[-1].date, freq)
        else:
            end_period = pd.Period(end_period, freq)

    if not currency:
        currency = opts["operating_currency"][0]

    # This is just to show types
    start_period: pd.Period = start_period
    end_period: pd.Period = end_period

    start_date_iso_str = start_period.start_time.strftime("%Y-%m-%d")
    end_date_iso_str = end_period.end_time.strftime("%Y-%m-%d")
    
    query = f"""
            select id, date, account, CONVERT(position,'{currency}',date) as amount, narration
            WHERE
                (account ~ '^Expenses') AND
                date >= {start_date_iso_str} AND
                date <= {end_date_iso_str}
            """
    df = beanquery2df(entries, opts,  query)
    df['period'] = pd.PeriodIndex(df['date'], freq=freq)
    
    df_pivot = get_bean_pivot(df, column = "period", max_row_levels=100, repeat_row_labels=False)
    
    # df_pivot = df_pivot[:f"amount ({currency})"]
    
    return df_pivot

In [62]:
expenses_df_pivot = get_expenses_df_pivot(entries, opts, "Y")
expenses_df_pivot

                                                        amount (IRAUSD)  \
period                                                             2015
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _                      0.0
          Fees        _             _        _                      0.0
Food      Alcohol     _             _        _                      0.0
          Coffee      _             _        _                      0.0
          Groceries   _             _        _                      0.0
          Restaurant  _             _        _                      0.0
Health    Dental      Insurance     _        _                      0.0
          Life        GroupTermLife _        _                      0.0
          Medical     Insurance     _        _                      0.0
          Vision      Insurance     _        _                      0.0
Home      Electricity _             _        _                      0.0
          Internet    _             _        _                      0.0
          Phone       _             _        _                      0.0
          Rent        _             _        _                      0.0
Taxes     Y2015       US            CityNYC  _                      0.0
                                    Federal  PreTax401k         18000.0
                                             _                      0.0
                                    Medicare _                      0.0
                                    SDI      _                      0.0
                                    SocSec   _                      0.0
                                    State    _                      0.0
          Y2016       US            CityNYC  _                      0.0
                                    Federal  PreTax401k             0.0
                                             _                      0.0
                                    Medicare _                      0.0
                                    SDI      _                      0.0
                                    SocSec   _                      0.0
                                    State    _                      0.0
          Y2017       US            CityNYC  _                      0.0
                                    Federal  PreTax401k             0.0
                                             _                      0.0
                                    Medicare _                      0.0
                                    SDI      _                      0.0
                                    SocSec   _                      0.0
                                    State    _                      0.0
Transport Tram        _             _        _                      0.0
Vacation  _           _             _        _                      0.0

                                                                           \
period                                                      2016     2017
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _               0.0      0.0
          Fees        _             _        _               0.0      0.0
Food      Alcohol     _             _        _               0.0      0.0
          Coffee      _             _        _               0.0      0.0
          Groceries   _             _        _               0.0      0.0
          Restaurant  _             _        _               0.0      0.0
Health    Dental      Insurance     _        _               0.0      0.0
          Life        GroupTermLife _        _               0.0      0.0
          Medical     Insurance     _        _               0.0      0.0
          Vision      Insurance     _        _               0.0      0.0
Home      Electricity _             _        _               0.0      0.0
          Internet    _             _        _               0.0      0.0
          Phone       _             _        _               0.0      0.0
          Rent        _             _        _               0.0      0.0
Taxes     Y2015       US            CityNYC  _               0.0      0.0
                                    Federal  PreTax401k      0.0      0.0
                                             _               0.0      0.0
                                    Medicare _               0.0      0.0
                                    SDI      _               0.0      0.0
                                    SocSec   _               0.0      0.0
                                    State    _               0.0      0.0
          Y2016       US            CityNYC  _               0.0      0.0
                                    Federal  PreTax401k  18000.0      0.0
                                             _               0.0      0.0
                                    Medicare _               0.0      0.0
                                    SDI      _               0.0      0.0
                                    SocSec   _               0.0      0.0
                                    State    _               0.0      0.0
          Y2017       US            CityNYC  _               0.0      0.0
                                    Federal  PreTax401k      0.0  18500.0
                                             _               0.0      0.0
                                    Medicare _               0.0      0.0
                                    SDI      _               0.0      0.0
                                    SocSec   _               0.0      0.0
                                    State    _               0.0      0.0
Transport Tram        _             _        _               0.0      0.0
Vacation  _           _             _        _               0.0      0.0

                                                        amount (USD)  \
period                                                          2015
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _                 71.60
          Fees        _             _        _                 48.00
Food      Alcohol     _             _        _                  0.00
          Coffee      _             _        _                 21.93
          Groceries   _             _        _               2054.00
          Restaurant  _             _        _               4538.74
Health    Dental      Insurance     _        _                 78.30
          Life        GroupTermLife _        _                656.64
          Medical     Insurance     _        _                739.26
          Vision      Insurance     _        _               1142.10
Home      Electricity _             _        _                780.00
          Internet    _             _        _                960.12
          Phone       _             _        _                764.30
          Rent        _             _        _              28800.00
Taxes     Y2015       US            CityNYC  _               4722.84
                                    Federal  PreTax401k         0.00
                                             _              28698.84
                                    Medicare _               2878.74
                                    SDI      _                 30.24
                                    SocSec   _               7000.04
                                    State    _               9857.16
          Y2016       US            CityNYC  _                  0.00
                                    Federal  PreTax401k         0.00
                                             _                  0.00
                                    Medicare _                  0.00
                                    SDI      _                  0.00
                                    SocSec   _                  0.00
                                    State    _                  0.00
          Y2017       US            CityNYC  _                  0.00
                                    Federal  PreTax401k         0.00
                                             _                  0.00
                                    Medicare _                  0.00
                                    SDI      _                  0.00
                                    SocSec   _                  0.00
                                    State    _                  0.00
Transport Tram        _             _        _               1440.00
Vacation  _           _             _        _                  0.00

                                                                             \
period                                                       2016      2017
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _             107.40     71.60
          Fees        _             _        _              48.00     36.00
Food      Alcohol     _             _        _              63.58      0.00
          Coffee      _             _        _              29.96     25.09
          Groceries   _             _        _            2367.32   1515.10
          Restaurant  _             _        _            4398.86   3146.23
Health    Dental      Insurance     _        _              75.40     52.20
          Life        GroupTermLife _        _             632.32    437.76
          Medical     Insurance     _        _             711.88    492.84
          Vision      Insurance     _        _            1099.80    761.40
Home      Electricity _             _        _             780.00    520.00
          Internet    _             _        _             959.42    639.97
          Phone       _             _        _             741.13    506.30
          Rent        _             _        _           28800.00  19200.00
Taxes     Y2015       US            CityNYC  _               0.00      0.00
                                    Federal  PreTax401k      0.00      0.00
                                             _             295.23      0.00
                                    Medicare _               0.00      0.00
                                    SDI      _               0.00      0.00
                                    SocSec   _               0.00      0.00
                                    State    _             274.92      0.00
          Y2016       US            CityNYC  _            4547.92      0.00
                                    Federal  PreTax401k      0.00      0.00
                                             _           27635.92    463.16
                                    Medicare _            2772.12      0.00
                                    SDI      _              29.12      0.00
                                    SocSec   _            7000.04      0.00
                                    State    _            9492.08    456.53
          Y2017       US            CityNYC  _               0.00   3148.56
                                    Federal  PreTax401k      0.00      0.00
                                             _               0.00  19132.56
                                    Medicare _               0.00   1919.16
                                    SDI      _               0.00     20.16
                                    SocSec   _               0.00   5067.72
                                    State    _               0.00   6571.44
Transport Tram        _             _        _            1320.00    960.00
Vacation  _           _             _        _               0.00      0.00

                                                        amount (VACHR)         \
period                                                            2015   2016
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _                     0.0    0.0
          Fees        _             _        _                     0.0    0.0
Food      Alcohol     _             _        _                     0.0    0.0
          Coffee      _             _        _                     0.0    0.0
          Groceries   _             _        _                     0.0    0.0
          Restaurant  _             _        _                     0.0    0.0
Health    Dental      Insurance     _        _                     0.0    0.0
          Life        GroupTermLife _        _                     0.0    0.0
          Medical     Insurance     _        _                     0.0    0.0
          Vision      Insurance     _        _                     0.0    0.0
Home      Electricity _             _        _                     0.0    0.0
          Internet    _             _        _                     0.0    0.0
          Phone       _             _        _                     0.0    0.0
          Rent        _             _        _                     0.0    0.0
Taxes     Y2015       US            CityNYC  _                     0.0    0.0
                                    Federal  PreTax401k            0.0    0.0
                                             _                     0.0    0.0
                                    Medicare _                     0.0    0.0
                                    SDI      _                     0.0    0.0
                                    SocSec   _                     0.0    0.0
                                    State    _                     0.0    0.0
          Y2016       US            CityNYC  _                     0.0    0.0
                                    Federal  PreTax401k            0.0    0.0
                                             _                     0.0    0.0
                                    Medicare _                     0.0    0.0
                                    SDI      _                     0.0    0.0
                                    SocSec   _                     0.0    0.0
                                    State    _                     0.0    0.0
          Y2017       US            CityNYC  _                     0.0    0.0
                                    Federal  PreTax401k            0.0    0.0
                                             _                     0.0    0.0
                                    Medicare _                     0.0    0.0
                                    SDI      _                     0.0    0.0
                                    SocSec   _                     0.0    0.0
                                    State    _                     0.0    0.0
Transport Tram        _             _        _                     0.0    0.0
Vacation  _           _             _        _                    72.0  168.0


period                                                    2017
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _             0.0
          Fees        _             _        _             0.0
Food      Alcohol     _             _        _             0.0
          Coffee      _             _        _             0.0
          Groceries   _             _        _             0.0
          Restaurant  _             _        _             0.0
Health    Dental      Insurance     _        _             0.0
          Life        GroupTermLife _        _             0.0
          Medical     Insurance     _        _             0.0
          Vision      Insurance     _        _             0.0
Home      Electricity _             _        _             0.0
          Internet    _             _        _             0.0
          Phone       _             _        _             0.0
          Rent        _             _        _             0.0
Taxes     Y2015       US            CityNYC  _             0.0
                                    Federal  PreTax401k    0.0
                                             _             0.0
                                    Medicare _             0.0
                                    SDI      _             0.0
                                    SocSec   _             0.0
                                    State    _             0.0
          Y2016       US            CityNYC  _             0.0
                                    Federal  PreTax401k    0.0
                                             _             0.0
                                    Medicare _             0.0
                                    SDI      _             0.0
                                    SocSec   _             0.0
                                    State    _             0.0
          Y2017       US            CityNYC  _             0.0
                                    Federal  PreTax401k    0.0
                                             _             0.0
                                    Medicare _             0.0
                                    SDI      _             0.0
                                    SocSec   _             0.0
                                    State    _             0.0
Transport Tram        _             _        _             0.0
Vacation  _           _             _        _           128.0

In [63]:
expenses_USD = expenses_df_pivot.loc[:, pd.IndexSlice[['amount (USD)'], :]         ]
expenses_USD

                                                        amount (USD)  \
period                                                          2015
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _                 71.60
          Fees        _             _        _                 48.00
Food      Alcohol     _             _        _                  0.00
          Coffee      _             _        _                 21.93
          Groceries   _             _        _               2054.00
          Restaurant  _             _        _               4538.74
Health    Dental      Insurance     _        _                 78.30
          Life        GroupTermLife _        _                656.64
          Medical     Insurance     _        _                739.26
          Vision      Insurance     _        _               1142.10
Home      Electricity _             _        _                780.00
          Internet    _             _        _                960.12
          Phone       _             _        _                764.30
          Rent        _             _        _              28800.00
Taxes     Y2015       US            CityNYC  _               4722.84
                                    Federal  PreTax401k         0.00
                                             _              28698.84
                                    Medicare _               2878.74
                                    SDI      _                 30.24
                                    SocSec   _               7000.04
                                    State    _               9857.16
          Y2016       US            CityNYC  _                  0.00
                                    Federal  PreTax401k         0.00
                                             _                  0.00
                                    Medicare _                  0.00
                                    SDI      _                  0.00
                                    SocSec   _                  0.00
                                    State    _                  0.00
          Y2017       US            CityNYC  _                  0.00
                                    Federal  PreTax401k         0.00
                                             _                  0.00
                                    Medicare _                  0.00
                                    SDI      _                  0.00
                                    SocSec   _                  0.00
                                    State    _                  0.00
Transport Tram        _             _        _               1440.00
Vacation  _           _             _        _                  0.00


period                                                       2016      2017
acc_L1    acc_L2      acc_L3        acc_L4   acc_L5
Financial Commissions _             _        _             107.40     71.60
          Fees        _             _        _              48.00     36.00
Food      Alcohol     _             _        _              63.58      0.00
          Coffee      _             _        _              29.96     25.09
          Groceries   _             _        _            2367.32   1515.10
          Restaurant  _             _        _            4398.86   3146.23
Health    Dental      Insurance     _        _              75.40     52.20
          Life        GroupTermLife _        _             632.32    437.76
          Medical     Insurance     _        _             711.88    492.84
          Vision      Insurance     _        _            1099.80    761.40
Home      Electricity _             _        _             780.00    520.00
          Internet    _             _        _             959.42    639.97
          Phone       _             _        _             741.13    506.30
          Rent        _             _        _           28800.00  19200.00
Taxes     Y2015       US            CityNYC  _               0.00      0.00
                                    Federal  PreTax401k      0.00      0.00
                                             _             295.23      0.00
                                    Medicare _               0.00      0.00
                                    SDI      _               0.00      0.00
                                    SocSec   _               0.00      0.00
                                    State    _             274.92      0.00
          Y2016       US            CityNYC  _            4547.92      0.00
                                    Federal  PreTax401k      0.00      0.00
                                             _           27635.92    463.16
                                    Medicare _            2772.12      0.00
                                    SDI      _              29.12      0.00
                                    SocSec   _            7000.04      0.00
                                    State    _            9492.08    456.53
          Y2017       US            CityNYC  _               0.00   3148.56
                                    Federal  PreTax401k      0.00      0.00
                                             _               0.00  19132.56
                                    Medicare _               0.00   1919.16
                                    SDI      _               0.00     20.16
                                    SocSec   _               0.00   5067.72
                                    State    _               0.00   6571.44
Transport Tram        _             _        _            1320.00    960.00
Vacation  _           _             _        _               0.00      0.00

In [64]:
expenses_sunburst_fig =get_sunburst_figure_from_pivot(expenses_USD, column_to_pick=('amount (USD)', '2015'))
expenses_sunburst_fig.update_layout(margin=dict(t=30, l=0, r=0, b=0),
                    autosize=True,
                    width=700,
                    height=700,
                    title_text="Expenses",
                    # title_x=0.5,
                    # title_y=0.95,
                    title_font=dict(size=20),
                    font=dict(size=12)
                   )
expenses_sunburst_fig.show()

## <a id='toc1_6_'></a>[Filtering spesific transactions](#toc0_)

In [65]:
def check_if_to_filter(entry):
    file = StringIO("")

    printer.print_entry(entry, file=file)
    file.seek(0)
    entry_str = file.read()

    if "Income:US:ETrade:Dividends" in entry_str:
        return True

filtered_entries = list(filter(check_if_to_filter, entries))

write_source = not IN_COLAB
display_entries(filtered_entries, write_source=write_source)